import { MeetingData } from "./types.js";

export const PRD_FIXTURE_MEETING: MeetingData = {
  id: "mtg_zoom_2026_08_07_001",
  title: "Payment Bug Triage",
  date: "2026-08-07T10:00:00Z",
  durationSeconds: 1800,
  attendees: ["Sarah Chen", "Alex Rivera", "Marcus Vance"],
  sourceFormat: "zoom-json",
  status: "ANALYZED",
  utterances: [
    {
      id: "utt_1",
      utteranceId: "mtg_zoom_2026_08_07_001:utt_1",
      speaker: "Sarah Chen",
      text: "Thanks everyone for joining emergency triage. We are seeing a spike in failed checkout transactions on the Stripe gateway.",
      timestamp: "00:00:05",
      utteranceIndex: 1,
    },
    {
      id: "utt_2",
      utteranceId: "mtg_zoom_2026_08_07_001:utt_2",
      speaker: "Alex Rivera",
      text: "I analyzed the logs from 09:00 UTC. The API timeouts are caused by unindexed queries in the database during high concurrency.",
      timestamp: "00:00:18",
      utteranceIndex: 2,
    },
    {
      id: "utt_3",
      utteranceId: "mtg_zoom_2026_08_07_001:utt_3",
      speaker: "Marcus Vance",
      text: "I think we should immediately roll back the v2.4 deployment to mitigate customer impact.",
      timestamp: "00:00:35",
      utteranceIndex: 3,
    },
    {
      id: "utt_4",
      utteranceId: "mtg_zoom_2026_08_07_001:utt_4",
      speaker: "Sarah Chen",
      text: "I strongly disagree with rolling back v2.4 because it contains critical security updates.",
      timestamp: "00:00:50",
      utteranceIndex: 4,
    },
    {
      id: "utt_5",
      utteranceId: "mtg_zoom_2026_08_07_001:utt_5",
      speaker: "Alex Rivera",
      text: "We decided to deploy the missing database index migration to production immediately instead of rolling back.",
      timestamp: "00:01:05",
      utteranceIndex: 5,
    },
    {
      id: "utt_6",
      utteranceId: "mtg_zoom_2026_08_07_001:utt_6",
      speaker: "Marcus Vance",
      text: "Marcus Vance will run the database index migration script by 11:30 AM today.",
      timestamp: "00:01:25",
      utteranceIndex: 6,
    },
    {
      id: "utt_7",
      utteranceId: "mtg_zoom_2026_08_07_001:utt_7",
      speaker: "Sarah Chen",
      text: "There is a risk that running concurrent index creation on the active primary DB could cause brief locks.",
      timestamp: "00:01:45",
      utteranceIndex: 7,
    },
  ],
  decisions: [
    {
      id: "dec_1",
      decision: "Deploy missing database index migration immediately instead of rolling back release",
      speaker: "Alex Rivera",
      timestamp: "00:01:05",
      exactQuote: "We decided to deploy the missing database index migration to production immediately instead of rolling back.",
      confidence: 0.95,
      context: "Emergency triage decision following Stripe checkout timeout spike",
      sourceUtteranceId: "mtg_zoom_2026_08_07_001:utt_5",
    },
  ],
  actionItems: [
    {
      id: "act_1",
      action: "Run database index migration script",
      owner: "Marcus Vance",
      deadline: "11:30 AM today",
      speaker: "Marcus Vance",
      timestamp: "00:01:25",
      exactQuote: "Marcus Vance will run the database index migration script by 11:30 AM today.",
      confidence: 0.92,
      priority: "CRITICAL",
      status: "PENDING",
      sourceUtteranceId: "mtg_zoom_2026_08_07_001:utt_6",
    },
  ],
  risks: [
    {
      id: "risk_1",
      risk: "Concurrent index creation on active primary database could cause table locks",
      riskType: "CONCERN",
      speaker: "Sarah Chen",
      timestamp: "00:01:45",
      exactQuote: "There is a risk that running concurrent index creation on the active primary DB could cause brief locks.",
      confidence: 0.88,
      severity: "HIGH",
      sourceUtteranceId: "mtg_zoom_2026_08_07_001:utt_7",
    },
  ],
  disagreements: [
    {
      id: "dis_1",
      topic: "Release v2.4 Rollback vs Immediate Index Patch",
      position1: "Roll back v2.4 deployment to mitigate customer impact immediately",
      speaker1: "Marcus Vance",
      timestamp1: "00:00:35",
      position2: "Do not roll back v2.4 because it contains critical security patches",
      speaker2: "Sarah Chen",
      timestamp2: "00:00:50",
      resolution: "Deploy database index migration script without rolling back v2.4",
      confidence: 0.91,
      sourceUtteranceId1: "mtg_zoom_2026_08_07_001:utt_3",
      sourceUtteranceId2: "mtg_zoom_2026_08_07_001:utt_4",
    },
  ],
};
